Document the Policy API concepts
open-cluster-management/website pull request #256
Opened 2022-05-04 20:31 UTC by mprahl

2022-05-04 20:31 UTC, mprahl commented
/cc @dhaiducek

2022-05-04 20:32 UTC, mprahl commented
/hold for review from @dhaiducek

2022-05-04 21:20 UTC, dhaiducek requested changes
Great explanations, @mprahl! 

I have some minor comments.

2022-05-04 21:20 UTC, dhaiducek commented on content/en/getting-started/integration/policy-framework.md
> +creates the "prod" namespace. At first, you may notice the `annotations`. These are standard
I think the YAML should be moved up so that it can be viewed first and then explained.
```suggestion
View a simple example of a `Policy` that embeds a `ConfigurationPolicy` policy template around
a namespace called "prod".
```yaml
YAML HERE
```
```

2022-05-04 21:20 UTC, dhaiducek commented on content/en/getting-started/integration/policy-framework.md
> +`inform` or `enforce` and overrides the `remediationAction` field on each policy template. When set
```suggestion
Next, you may notice the optional `spec.remediationAction` field. This dictates if the policy controller should
`inform` or `enforce` when violations are found and overrides the `remediationAction` field on each policy template. When set
```

2022-05-04 21:20 UTC, dhaiducek commented on content/en/getting-started/integration/policy-framework.md
> +desired state when necessary.
It doesn't really apply to the config controller, so maybe this isn't necessary to note...
```suggestion
desired state when necessary and feasible.
```

2022-05-04 21:20 UTC, dhaiducek commented on content/en/getting-started/integration/policy-framework.md
> +`MustHave` which means, the `prod` `Namespace` object will be created if it doesn't exist. Other
```suggestion
`MustHave` which means the `prod` `Namespace` object will be created if it doesn't exist. Other
```

2022-05-04 21:20 UTC, dhaiducek commented on content/en/getting-started/integration/policy-framework.md
> +When the `Policy` is bound to a [Placement](../../concepts/placement.md), the `Policy` status will
```suggestion
When the `Policy` is bound to a [Placement](../../../concepts/placement), the `Policy` status will
```

2022-05-04 21:20 UTC, dhaiducek commented on content/en/getting-started/integration/policy-framework.md
> +eventually look like the following:
```suggestion
report on each cluster that matched the bound Placement:
```

2022-05-05 02:34 UTC, qiujian16 commented on content/en/getting-started/integration/policy-controllers.md
> +[policy-collection](https://github.com/stolostron/policy-collection). Note that these
please do not use stolostron org here.

2022-05-05 13:10 UTC, mprahl commented on content/en/getting-started/integration/policy-controllers.md
> +[policy-collection](https://github.com/stolostron/policy-collection). Note that these
We don't have an equivalent in open-cluster-management-io yet. I was just updating the GitHub org name.

2022-05-05 13:27 UTC, JustinKuli commented on content/en/getting-started/integration/policy-framework.md
> +- *Policy Templates* are the policies that perform a desired check or action. An example of this are
Grammar nit:
```suggestion
- *Policy Templates* are the policies that perform a desired check or action. An example of this is
```

It still sounds weird, but since it's one example, the verb should be singular I think? Maybe just worth re-writing the sentence to avoid it, like "For example, ConfigurationPolicy objects are embedded..."

2022-05-05 13:28 UTC, JustinKuli commented on content/en/getting-started/integration/policy-framework.md
> +  deployable unit. Embedded *Policy Templates* are distributed to applicable managed clusters and
Not sure if we should specify that a Policy is the smallest deployable unit *on the hub cluster*.

2022-05-05 13:30 UTC, JustinKuli commented on content/en/getting-started/integration/policy-framework.md
> +A `Policy` is a grouping mechanism for *Policy Templates* and is the smallest deployable unit.
Nit: This sentence is just a repeat of before.

2022-05-05 13:32 UTC, JustinKuli commented on content/en/getting-started/integration/policy-framework.md
> +View a simple example of a `Policy` that embeds a `ConfigurationPolicy` policy template around a
Nit, it just sounds a little weird.
```suggestion
View a simple example of a `Policy` that embeds a `ConfigurationPolicy` policy template to create a
```

2022-05-05 13:33 UTC, JustinKuli commented on content/en/getting-started/integration/policy-framework.md
> +to `enforce`, the underlying policy templates apply the desired state when necessary and feasible.
Optional nit:
```suggestion
to `enforce`, the policy controller applies the desired state when necessary and feasible.
```

2022-05-05 13:41 UTC, mprahl commented on content/en/getting-started/integration/policy-framework.md
> +A `Policy` is a grouping mechanism for *Policy Templates* and is the smallest deployable unit.
I included it again so that links directly to the Policy section explain it all without the user having to read the Overview section.

2022-05-05 13:50 UTC, dhaiducek commented on content/en/getting-started/integration/policy-framework.md
> +View a simple example of a `Policy` that embeds a `ConfigurationPolicy` policy template around a
"around" was my proposed change, though I agree it's not great. With the ability to "inform" on the policy or set it to "mustnothave", "create" didn't quite seem to fit the nuances of what ConfigurationPolicy does. I landed on "around" in the vein of the previous "embeds", though maybe "manage", "govern", or "monitor" would be better?

2022-05-05 13:52 UTC, JustinKuli commented on content/en/getting-started/integration/policy-framework.md
> +View a simple example of a `Policy` that embeds a `ConfigurationPolicy` policy template around a
Good point, "manage" might be better

2022-05-05 13:52 UTC, mprahl commented on content/en/getting-started/integration/policy-framework.md
> +View a simple example of a `Policy` that embeds a `ConfigurationPolicy` policy template around a
I like "manage". Thanks for the suggestion!

2022-05-05 20:22 UTC, dhaiducek requested changes
I'm pretty sure the links still won't work. I might be proved wrong, but the URLs in the actual site all have a trailing slash, so I think you'll need to update all of these:
```
./sibling-page --> ../sibling-page
../../concept-page --> ../../../concept-page
```
to get up into the parent. Alternatively, you can do this for the concept pages, which might be a bit cleaner:
```
../../concept-page --> /concepts/concept-page
```

2022-05-06 00:06 UTC, qiujian16 commented on content/en/getting-started/integration/policy-controllers.md
> +[policy-collection](https://github.com/stolostron/policy-collection). Note that these
probably remove this section if we do not have an equivalent. We got some feedback before on having stolostron org in the website so I have to fix in this https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/pull/235.

2022-05-06 01:24 UTC, mprahl commented
> I'm pretty sure the links still won't work. I might be proved wrong, but the URLs in the actual site all have a trailing slash, so I think you'll need to update all of these:
> 
> ```
> ./sibling-page --> ../sibling-page
> ../../concept-page --> ../../../concept-page
> ```
> 
> to get up into the parent. Alternatively, you can do this for the concept pages, which might be a bit cleaner:
> 
> ```
> ../../concept-page --> /concepts/concept-page
> ```

I'm confused because the links work in markdown so I don't know why it wouldn't when generated for the website. @mikeshng are you able to provide some help here?

2022-05-06 01:25 UTC, mprahl commented on content/en/getting-started/integration/policy-controllers.md
> +[policy-collection](https://github.com/stolostron/policy-collection). Note that these
@qiujian16 okay, I'll remove it but it's too bad since it's great content. I'll see if we can move that repo to the community in the near future.

2022-05-06 15:47 UTC, dhaiducek commented
If you're looking for an example in the site for a link that works this way:
https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/blob/d237120ac80dfe0686647e15256b0bbcc586ab6f/content/en/concepts/placement.md?plain=1#L23

2022-05-06 15:51 UTC, mikeshng commented
Hi guys, sorry I missed the message.

You should run:
```
make server
```
and then visit the local generated website with a browser to verify your changes work properly. This website is generated using the Hugo framework. You can create pages using .MD but for links it might work differently.

More details in https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/blob/main/README.md

2022-05-06 15:59 UTC, dhaiducek commented
It would be really nice if the live site and the Markdown worked consistently, but removing that trailing slash is an issue for another day since it'd probably require quite a few link updates...

2022-05-06 16:10 UTC, mprahl commented
Thanks @mikeshng and @dhaiducek! I fixed the links and this ready for review again.

2022-05-06 16:24 UTC, dhaiducek commented on content/en/getting-started/integration/policy-controllers.md
> +[`Policy` API concept section](policy-framework#policy).
I think this link needs to be fixed.

2022-05-06 16:33 UTC, mprahl commented on content/en/getting-started/integration/policy-controllers.md
> +[`Policy` API concept section](policy-framework#policy).
Good catch. Thanks!

2022-05-06 16:42 UTC, dhaiducek requested changes
I like that you're using the full path, so I found some others that could be updated and then I think this should be good to go!

2022-05-06 16:42 UTC, dhaiducek commented on content/zh/getting-started/integration/policy-controllers.md
> +   [Bind ManagedClusterSet to a namespace](../../../concepts/managedclusterset#bind-managedclusterset-to-a-namespace)
```suggestion
   [Bind ManagedClusterSet to a namespace](/concepts/managedclusterset#bind-managedclusterset-to-a-namespace)
```

2022-05-06 16:42 UTC, dhaiducek commented on content/en/getting-started/quick-start/_index.md
> +  - [Deploy Policies onto a managed cluster](../integration/policy-framework)
```suggestion
  - [Deploy Policies onto a managed cluster](/getting-started/integration/policy-framework)
```

2022-05-06 16:42 UTC, dhaiducek commented on content/zh/getting-started/integration/policy-controllers.md
> +  [Policy Framework](../policy-framework) for more information.
```suggestion
  [Policy Framework](/getting-started/integration/policy-framework) for more information.
```

2022-05-06 17:11 UTC, dhaiducek approved these changes
LGTM! Thanks, @mprahl!

2022-05-06 17:37 UTC, mikeshng commented
/approve

2022-05-06 18:01 UTC, mprahl commented
/unhold

2022-05-06 18:02 UTC, merged