add cluster lifecycle
open-cluster-management/website pull request #58
Opened 2021-04-12 12:41 UTC by hanqiuzh

2021-04-12 13:05 UTC, hanqiuzh commented
/assign @leena-jawale @itdove

2021-04-12 13:25 UTC, leena-jawale commented
/approve

2021-04-12 13:31 UTC, mikeshng commented on content/getting-started/install-cluster-lifecycle.md
> +klusterlet-addon-workmgr-746bbf5848-7z9m4    1/1     Running   0          11s
FYI @ycao56

2021-04-12 13:38 UTC, hanqiuzh commented on content/getting-started/install-cluster-lifecycle.md
> +klusterlet-addon-workmgr-746bbf5848-7z9m4    1/1     Running   0          11s
@qiujian16 workmgr will crash as hub doesn't have ocm installed (missing crds), do you know if there is any plan to doc the ocm installation?

2021-04-13 01:54 UTC, qiujian16 commented on content/getting-started/install-cluster-lifecycle.md
> +klusterlet-addon-workmgr-746bbf5848-7z9m4    1/1     Running   0          11s
will you need this https://github.com/open-cluster-management/website/pull/60 as the prereq?

2021-04-13 02:45 UTC, hanqiuzh commented on content/getting-started/install-cluster-lifecycle.md
> +klusterlet-addon-workmgr-746bbf5848-7z9m4    1/1     Running   0          11s
no, this only requires Hive+Cluster-Manager to install & run.

@mikeshng if #60  for acm-installer is ready, do we still need this install instructions?

2021-04-13 14:13 UTC, mikeshng commented on content/getting-started/install-cluster-lifecycle.md
> +klusterlet-addon-workmgr-746bbf5848-7z9m4    1/1     Running   0          11s
@qiujian16 @hanqiuzh I will need to discuss with the install team. I don't think our install instruction on our website is good enough for a completely outsider to come in and use. Let me get back to you on this.

2021-04-19 19:55 UTC, mikeshng commented on content/getting-started/install-cluster-lifecycle.md
> +klusterlet-addon-workmgr-746bbf5848-7z9m4    1/1     Running   0          11s
@hanqiuzh we have to hide the install instructions as its not ready for community consumption. 
Could you please update your  instructions install the prereqs if its not there already?

2021-04-20 18:23 UTC, mikeshng reviewed
This is an amazing doc. Small fixes needed

2021-04-20 18:23 UTC, mikeshng commented on content/getting-started/install-cluster-lifecycle.md
> +Install [cluster-manager](install-hub.md) on the hub.
Change to 
```
[Install Cluster Manager](../install-cluster-manager) for more information.
```
The framework that renders this file is not the same as just plain render of md file so it needs to have the above for the link to work. Also, we renamed the file.

2021-04-20 18:23 UTC, mikeshng commented on content/getting-started/install-cluster-lifecycle.md
> +kubectl apply -k overlays/community
add `cd managedcluster-import-controller` before this apply

2021-04-20 18:23 UTC, mikeshng commented on content/getting-started/install-cluster-lifecycle.md
> +kubectl apply -k overlays/community
add `cd klusterlet-addon-controller` before this apply

2021-04-20 18:23 UTC, mikeshng commented on content/getting-started/install-cluster-lifecycle.md
> +
maybe add 
`kubectl get po -n open-cluster-management | grep klusterlet-addon-controller` similar to the managedcluster import controller above?

2021-04-20 21:59 UTC, hanqiuzh commented on content/getting-started/install-cluster-lifecycle.md
> +kubectl apply -k overlays/community
added after git clone

2021-04-20 22:00 UTC, hanqiuzh commented on content/getting-started/install-cluster-lifecycle.md
> +kubectl apply -k overlays/community
added after git clone

2021-04-20 22:01 UTC, hanqiuzh commented on content/getting-started/install-cluster-lifecycle.md
> +Install [cluster-manager](install-hub.md) on the hub.
so all the relative links will be (../file-name-without-md-extension)?

2021-04-20 22:01 UTC, hanqiuzh commented on content/getting-started/install-cluster-lifecycle.md
> +Install [cluster-manager](install-hub.md) on the hub.
updated all relative links, please review again

2021-04-21 13:43 UTC, mikeshng commented on content/getting-started/install-cluster-lifecycle.md
> +klusterlet-addon-workmgr-746bbf5848-7z9m4    1/1     Running   0          11s
@hanqiuzh after talking with @qiujian16 we agreed that the community cluster lifecycle piece should just be able importing the cluster and not have to worry about the addons. Could you please remove the section about `klusterlet-addon-controller`.

2021-04-21 16:45 UTC, mikeshng commented on content/getting-started/register-cluster.md
> +If you have installed [cluster-lifecycle](install-cluster-lifecycle.md), you can follow this [instruction](install-cluster-lifecycle.md#manually_register_a_cluster) to register a managed cluster.
@hanqiuzh sorry, I didn't catch this earlier but can you fix the link here for `[cluster-lifecycle](install-cluster-lifecycle.md)` and `[instruction](install-cluster-lifecycle.md#manually_register_a_cluster) `

it should be something like `[cluster-lifecycle](../install-cluster-lifecycle)`
and
`[instruction](../install-cluster-lifecycle#manually-register-a-cluster)` <- could you check if it should be `-` instead of `_`

2021-04-21 20:22 UTC, cadawson requested changes
I added some review suggestions. I could not add comments past line 36 in the second file. I am not sure why. Let me know if you have any questions. Thanks!

2021-04-21 20:22 UTC, cadawson commented on content/getting-started/register-cluster.md
>  If you have not already done so, clone the `registration-operator`.
1. If you have not already done so, clone the `registration-operator` repo.
```Shell
git clone https://github.com/open-cluster-management/registration-operator
```

2021-04-22 14:12 UTC, dockerymick reviewed
I left a few comments here as well

2021-04-22 14:12 UTC, dockerymick commented on content/getting-started/install-cluster-lifecycle.md
> +Note: `CLUSTER_NAME` should be same as the clusterdeployment's resource name, and `CLUSTER_NAME` should also be same as the clusterdeployment's namespace name.
Bold the word Note, for example, **Note**:

2021-04-22 14:12 UTC, dockerymick commented on content/getting-started/install-cluster-lifecycle.md
> +On the **hub**, run the following command to two yaml files:
Based on my previous [PR](https://github.com/open-cluster-management/website/pull/63#discussion_r616747927) that I created for the GRC updates, I was told that hub is now referenced as the **cluster manager**. Is there a reason why it needs to be bold? I would consider using italics instead of bold. 

Also change "yaml" to `yaml` (make yaml monospace), please do this for each "yaml" instance

2021-04-22 14:12 UTC, dockerymick commented on content/getting-started/install-cluster-lifecycle.md
> +On the **managed cluster**, apply the yaml files:
If emphasis is required for managed cluster, please consider italicizing "managed cluster"

2021-04-22 14:12 UTC, dockerymick commented on content/getting-started/install-cluster-lifecycle.md
> +Verify cluster is available on the **hub**:
Change hub to cluster manager

2021-04-22 14:12 UTC, dockerymick commented on content/getting-started/register-cluster.md
> +If you have installed [cluster-lifecycle](install-cluster-lifecycle.md), you can follow this [instruction](install-cluster-lifecycle.md#manually_register_a_cluster) to register a managed cluster.
change "Cluster-Lifecycle" to "Cluster Lifecycle"

If you have installed cluster lifecycle, you can follow the instructions from the section, Manually register a cluster.

2021-04-22 21:30 UTC, hanqiuzh commented on content/getting-started/install-cluster-lifecycle.md
> +[Install Cluster Manager](../install-cluster-manager) for more information.
yes, they are separate, will take the `Install a cluster manager. See Install Cluster Manager for more information.` one

2021-04-22 21:49 UTC, hanqiuzh commented on content/getting-started/install-cluster-lifecycle.md
> +On the **hub**, run the following command to two yaml files:
cluster manager vs managed cluster 😵  and yes, will use italics

2021-04-23 00:37 UTC, qiujian16 commented
/approve

I think it looks good, @mikeshng leave it to you for a lgtm tag

2021-04-23 00:48 UTC, hanqiuzh commented on content/getting-started/register-cluster.md
>  If you have not already done so, clone the `registration-operator`.
this will be in another pr maybe, to modify all the format. As this instruction is for register cluster 😂

2021-04-23 19:00 UTC, dockerymick commented on content/getting-started/install-cluster-lifecycle.md
> +   Replace the `CLUSTER_NAME` with the cluster's name you are using.
Remove possession for cluster. I suggest "replace the `CLUSTER_NAME` with the cluster name that you are using"

2021-04-23 19:02 UTC, dockerymick commented on content/getting-started/install-cluster-lifecycle.md
> +   **Note**: `CLUSTER_NAME` should be same as both the clusterdeployment's resource name and the clusterdeployment's namespace name.
Since you are referring to the resource name, i suggest that you change clusterdeployment's resource to `ClusterDeployment` resource name and `ClusterDeployment` namespace name.

2021-04-23 19:03 UTC, dockerymick approved these changes
Indentation looks good! I made a few more comments, very small changes tho

2021-04-23 19:04 UTC, merged

2021-04-23 19:10 UTC, dockerymick commented
I didn't know the PR would merge automatically after i approved it @hanqiuzh could you address my comments in a different PR? Or I can fork the repo and make the PR