enhancement to open-cluster-management.io
open-cluster-management/website pull request #72
Opened 2021-05-01 20:04 UTC by mikeshng

- front page enhancement: add more pictures to show integrations with other open source software
- divide pieces into core components and addons/integrations

@qiujian16 could you please provide some feedback. If you think this is ok, I want to get the doc developers to review it before merging. Thanks.

![image](https://user-images.githubusercontent.com/58747157/116793724-64ecf800-aa96-11eb-87a6-10a14a67d9a2.png)

Signed-off-by: Mike Ng <ming@redhat.com>

2021-05-04 15:08 UTC, swopebe commented
@qiujian16 @mikeshng it would help if you could make sure the doc team (Myself, Chris, Mikela) all could edit your PRs into your branches or forks.... seems on this one, I cannot assign myself or edit so I will make comments.

2021-05-04 15:11 UTC, mikeshng commented
/assign swopebe

@swopebe I am not sure if this will help but we will have to wait for Qiu Jian to be back from vacation to modify access control. I don't have enough permission to add you.

2021-05-04 15:18 UTC, swopebe requested changes
Please make the headers sentence-style, which means only proper names are capitalized and the first word.

2021-05-04 15:18 UTC, swopebe commented on content/_index.md
> +Install and create a [Cluster Manager](https://operatorhub.io/operator/cluster-manager) on your _hub_ cluster.
sentence case: Cluster manager

2021-05-04 15:18 UTC, swopebe commented on content/_index.md
> +Enable the Policy Framework addon which provides governance capability to gain visibility, and drive remediation for various security and configuration aspects to help meet such enterprise standards.
comma after addon:

addon, which

2021-05-04 15:18 UTC, swopebe commented on content/_index.md
> +Enable the Policy Framework addon which provides governance capability to gain visibility, and drive remediation for various security and configuration aspects to help meet such enterprise standards.
also, this should be add-on

2021-05-04 15:18 UTC, swopebe commented on content/_index.md
> +Enable the Policy Framework addon which provides governance capability to gain visibility, and drive remediation for various security and configuration aspects to help meet such enterprise standards.
Please change all addons to add-ons.

2021-05-04 15:18 UTC, swopebe commented on content/_index.md
> +Enable the Policy Framework addon which provides governance capability to gain visibility, and drive remediation for various security and configuration aspects to help meet such enterprise standards.
See some of our Word of the day posts:
https://coreos.slack.com/archives/CUHCCV19P/p1607618517043100

2021-05-04 15:18 UTC, swopebe commented on content/_index.md
> +Enable the Application Lifecycle Management addon for delivery, upgrade, and configuration of applications on Kubernetes clusters. For more details see [Application Management](getting-started/integr
Change to: Application lifecycle management add-on

2021-05-04 15:18 UTC, swopebe commented on content/_index.md
> +Using OKD and Hive technologies, enable the Cluster Lifecycle Management addon to unlock enhanced multiclusters management capabilities. For more details see [Cluster Lifecycle Management](getting-st
Cluster lifecycle management add-on

2021-05-04 15:18 UTC, swopebe commented on content/_index.md
> +Using OKD and Hive technologies, enable the Cluster Lifecycle Management addon to unlock enhanced multiclusters management capabilities. For more details see [Cluster Lifecycle Management](getting-st
[Cluster lifecycle management]

2021-05-04 15:18 UTC, swopebe commented on content/_index.md
> +Using OKD and Hive technologies, enable the Cluster Lifecycle Management addon to unlock enhanced multiclusters management capabilities. For more details see [Cluster Lifecycle Management](getting-st
Change: multiclusters
to multicluster

No need for plural or possessive

2021-05-04 15:18 UTC, swopebe commented on content/getting-started/core/_index.md
> +Install the core control plane of open cluster management that includes cluster registration and manifests distribution on the _hub_ cluster, then install the klusterlet agent on the _manage_ cluster
I would make this two sentences. They are two steps, really.

2021-05-04 15:18 UTC, swopebe commented on content/getting-started/core/register-cluster.md
> +Ensure the open-cluster-management cluster manager is installed on the hub cluster. See [Cluster Manager](../cluster-manager) for more information.
We write open-cluster-management sometimes, then open cluster management... We need to pick one. I mostly see the first option and it works if you want to choose that one.

2021-05-04 15:18 UTC, swopebe commented on content/getting-started/core/register-cluster.md
> +title: Klusterlet Agent
lower case a

2021-05-04 15:18 UTC, swopebe commented on content/getting-started/core/cluster-manager.md
>  weight: 1
lower case M

2021-05-04 15:18 UTC, swopebe commented on content/getting-started/integration/policy-framework.md
> +title: Policy Framework
Lower case f

2021-05-04 15:18 UTC, swopebe commented on content/getting-started/integration/policy-controllers.md
> +weight: 2
lower case c

2021-05-04 15:19 UTC, swopebe commented on content/getting-started/integration/app-lifecycle.md
> +You must meet the following prerequisites to install the application lifecycle management addon:
fix name and add-on here, as well

2021-05-04 18:17 UTC, mikeshng commented
Thank you Brandi for the review. Added commit https://github.com/open-cluster-management/website/pull/72/commits/6ed94b0e4b0fcd39538e1771ba28335c6a0916cb to address all the issues.

2021-05-05 12:12 UTC, cadawson requested changes
Added a few more comments. Looks good!

2021-05-05 12:12 UTC, cadawson commented on content/getting-started/integration/app-lifecycle.md
>  Clone the `multicloud-operators-subscription`
Clone the `multicloud-operators-subscription` repository.

2021-05-05 12:12 UTC, cadawson commented on content/_index.md
>  - Define API for policy definition to ensure desired configuration and security settings are auditable or enforceable.
I think it would be easier to follow if ordered lists were used for the procedures.

2021-05-05 16:22 UTC, mikeshng commented
added https://github.com/open-cluster-management/website/pull/72/commits/eb19c57ed9d15999358deb500410ced4638c2bf8 based on Christopher's feedback.

2021-05-05 16:22 UTC, mikeshng commented on content/_index.md
> +Install and create a [Klusterlet agent](https://operatorhub.io/operator/klusterlet) on your _manage_ cluster.
done as suggested. Thanks.

2021-05-05 16:22 UTC, mikeshng commented on content/_index.md
> +Enable the Policy Framework addon which provides governance capability to gain visibility, and drive remediation for various security and configuration aspects to help meet such enterprise standards.
done as suggested. Thanks.

2021-05-05 16:22 UTC, mikeshng commented on content/getting-started/core/_index.md
> +Install the core control plane of open cluster management that includes cluster registration and manifests distribution on the _hub_ cluster, then install the klusterlet agent on the _manage_ cluster
done as suggested. Thanks.

2021-05-05 16:23 UTC, mikeshng commented on content/getting-started/core/cluster-manager.md
> +title: Cluster Manager
done as suggested. Thanks.

2021-05-05 16:23 UTC, mikeshng commented on content/getting-started/core/register-cluster.md
>  Prepare another Kubernetes cluster to function as the managed cluster. For example, use [kind](https://kind.sigs.k8s.io/docs/user/quick-start) to create another cluster as below. To use kind, you wil
done as suggested. Thanks.

2021-05-05 16:23 UTC, mikeshng commented on content/getting-started/integration/app-lifecycle.md
>  Clone the `multicloud-operators-subscription`
done as suggested. Thanks.

2021-05-06 02:23 UTC, qiujian16 commented
/hold
/lgtm

it looks good to me, feel free to unhold

2021-05-06 13:31 UTC, mikeshng commented
/unhold

Should be good to merge as all the feedbacks has been addressed.

2021-05-06 13:32 UTC, merged