heavy refactor to modernize look and feel
open-cluster-management/website pull request #78
Opened 2021-05-25 20:57 UTC by mikeshng

- modernize the look and feel (with least amount of work as possible)
- update hugo theme
- updated logo
- emphasis more content on core foundation apis such as registration, manifestwork and placement
- removed contents that are no longer valid in community (ui, install, clc etc.)
- less of a "doc" upon entry.

The entry page now looks like the following:

![image](https://user-images.githubusercontent.com/58747157/119566636-5df59480-bd79-11eb-827f-bf38b3cf895c.png)

clicking the quick start will bring you to

![image](https://user-images.githubusercontent.com/58747157/119567227-0efc2f00-bd7a-11eb-917f-89c708cacd2b.png)

Signed-off-by: Mike Ng <ming@redhat.com>

2021-05-26 02:54 UTC, qiujian16 commented
should we review it in one of the community meeting?

2021-05-27 04:08 UTC, qiujian16 commented
/assign @swopebe

2021-05-27 17:55 UTC, swopebe requested changes
see comments

2021-05-27 17:55 UTC, swopebe commented on content/_index.md
> +The Open Cluster Management is a community-driven project focused on multicluster and multicloud scenarios for Kubernetes apps. Open APIs are evolving within this project for cluster registration, wo
Open Cluster Management is a community-driven project focused on multicluster and multicloud scenarios for Kubernetes apps. Open APIs are evolving within this project for cluster registration, work distribution, dynamic placement of policies and workloads, and much more.

small change here, just eliminate the `The`

2021-05-27 17:55 UTC, swopebe commented on content/_index.md
> +Registration of multiple clusters to a hub cluster to place them under management.
let's say "for management" -- under is directional and can be an accessibility hit.

2021-05-27 17:55 UTC, swopebe commented on content/_index.md
> +Work API that enables resources to be applied to managed clusters from a hub cluster.
SO here you need the THE. The work API....

2021-05-27 17:55 UTC, swopebe commented on themes/hugo-geekdoc/CONTRIBUTING.md
> +If you think you have found a **security issue**, please do not mention it in this repository.
Confused about this, I thought we ironed out a common doc for this one? If we are changing that, this needs just a bit of work.

2021-05-27 18:24 UTC, mikeshng commented on themes/hugo-geekdoc/CONTRIBUTING.md
> +If you think you have found a **security issue**, please do not mention it in this repository.
This is under `themes` and not something we will display.

2021-05-27 18:25 UTC, mikeshng commented on content/_index.md
> +Work API that enables resources to be applied to managed clusters from a hub cluster.
Thanks. Fixed in https://github.com/open-cluster-management/website/pull/78/commits/e1f34f0967b8fe5d9c6092b69e249d65c77a10d9

2021-05-27 18:25 UTC, mikeshng commented on content/_index.md
> +Registration of multiple clusters to a hub cluster to place them under management.
Thanks. Fixed in https://github.com/open-cluster-management/website/pull/78/commits/e1f34f0967b8fe5d9c6092b69e249d65c77a10d9

2021-05-27 18:25 UTC, mikeshng commented on content/_index.md
> +The Open Cluster Management is a community-driven project focused on multicluster and multicloud scenarios for Kubernetes apps. Open APIs are evolving within this project for cluster registration, wo
Thanks. Fixed in https://github.com/open-cluster-management/website/pull/78/commits/e1f34f0967b8fe5d9c6092b69e249d65c77a10d9

2021-05-27 19:43 UTC, swopebe approved these changes

2021-05-27 19:44 UTC, merged